let projetos = [
  {
    id: 1,
    name: "Sistema de Vendas",
    description: "Desenvolvimento de sistema completo para gestão de vendas",
    status: "em-andamento",
    progress: 75,
    equipe: [
      "João Silva",
      "Maria Santos",
      "Pedro Costa",
      "Ana Lima",
      "Carlos Oliveira",
    ],
    deadline: "2024-02-15",
    createdAt: "2024-01-01",
    priority: "alta",
  },
  {
    id: 2,
    name: "App Celular",
    description: "Aplicativo celular para clientes",
    status: "em-desenvolvimento",
    progress: 45,
    equipe: ["Maria Santos", "Pedro Costa", "Ana Lima"],
    deadline: "2024-03-01",
    createdAt: "2024-01-10",
    priority: "media",
  },
  {
    id: 3,
    name: "Website Corporativo",
    description: "Novo site institucional da empresa",
    status: "quase-concluido",
    progress: 90,
    equipe: ["João Silva", "Ana Lima", "Carlos Oliveira", "Lucia Ferreira"],
    deadline: "2024-01-30",
    createdAt: "2023-12-15",
    priority: "alta",
  },
  {
    id: 4,
    name: "Sistema de RH",
    description: "Plataforma para gestão de recursos humanos",
    status: "planejamento",
    progress: 10,
    equipe: ["Pedro Costa", "Lucia Ferreira"],
    deadline: "2024-04-15",
    createdAt: "2024-01-20",
    priority: "baixa",
  },
];

let tarefas = [
  {
    id: 1,
    title: "Implementar sistema de autenticação",
    description: "Desenvolver login, logout e recuperação de senha",
    status: "em-progresso",
    priority: "alta",
    projetos: "Sistema de Vendas",
    assignee: "João Silva",
    deadline: "2024-01-30",
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    title: "Criar telas do dashboard",
    description: "Desenvolver interface do painel administrativo",
    status: "todo",
    priority: "alta",
    projetos: "Sistema de Vendas",
    assignee: "Maria Santos",
    deadline: "2024-02-05",
    createdAt: "2024-01-16",
  },
  {
    id: 3,
    title: "Configurar banco de dados",
    description: "Setup inicial do PostgreSQL e migrations",
    status: "concluida",
    priority: "alta",
    projetos: "Sistema de Vendas",
    assignee: "Pedro Costa",
    deadline: "2024-01-25",
    createdAt: "2024-01-10",
  },
  {
    id: 4,
    title: "Testes de usabilidade",
    description: "Realizar testes com usuários finais",
    status: "todo",
    priority: "media",
    projetos: "App Celular",
    assignee: "Ana Lima",
    deadline: "2024-02-10",
    createdAt: "2024-01-18",
  },
];

const eventos = [
    {
      id: 1,
      title: "Reunião de Sprint",
      date: "2024-01-25",
      time: "09:00",
      type: "meeting",
      participants: ["João Silva", "Maria Santos", "Pedro Costa"],
      description: "Reunião semanal de planejamento do sprint",
    },
    {
      id: 2,
      title: "Review do Projeto",
      date: "2024-01-26",
      time: "14:30",
      type: "review",
      participants: ["Ana Lima", "Carlos Oliveira"],
      description: "Revisão do progresso do projeto Sistema de Vendas",
    },
    {
      id: 3,
      title: "Apresentação para Cliente",
      date: "2024-01-30",
      time: "10:00",
      type: "presentation",
      participants: ["João Silva", "Maria Santos", "Ana Lima"],
      description: "Apresentação final do projeto Website Corporativo",
    },
  ]
  
  const equipes = [
    {
      id: 1,
      name: "Desenvolvimento Frontend",
      description: "Equipe responsável pelo desenvolvimento da interface do usuário",
      members: ["Maria Santos", "Ana Lima", "Carlos Oliveira"],
      leader: "Maria Santos",
      projetos: ["Website Corporativo", "App Celular"],
      createdAt: "2024-01-01",
    },
    {
      id: 2,
      name: "Desenvolvimento Backend",
      description: "Equipe responsável pelo desenvolvimento do servidor e APIs",
      members: ["João Silva", "Pedro Costa", "Lucia Ferreira"],
      leader: "João Silva",
      projetos: ["Sistema de Vendas", "Sistema de RH"],
      createdAt: "2024-01-01",
    },
  ]
  
  let avisos = [
    {
      id: 1,
      title: "Nova política de trabalho remoto",
      content: "A partir de fevereiro, todos os funcionários poderão trabalhar remotamente até 3 dias por semana.",
      type: "policy",
      priority: "alta",
      author: "RH",
      publishedAt: "2024-01-20",
      expiresAt: "2024-03-01",
    },
    {
      id: 2,
      title: "Manutenção programada do sistema",
      content: "O sistema ficará indisponível no sábado das 02:00 às 06:00 para manutenção.",
      type: "maintenance",
      priority: "media",
      author: "TI",
      publishedAt: "2024-01-22",
      expiresAt: "2024-01-27",
    },
  ]
  
  const chatGrupos = [
    {
      id: 1,
      name: "Geral",
      type: "public",
      members: ["João Silva", "Maria Santos", "Pedro Costa", "Ana Lima", "Carlos Oliveira"],
      messages: [
        {
          id: 1,
          sender: "Maria Santos",
          content: "Bom dia pessoal! Como estão os projetos hoje?",
          timestamp: "2024-01-25 09:15",
          type: "text",
        },
        {
          id: 2,
          sender: "João Silva",
          content: "Bom dia! O Sistema de Vendas está 75% concluído.",
          timestamp: "2024-01-25 09:17",
          type: "text",
        },
      ],
    },
    {
      id: 2,
      name: "Desenvolvimento",
      type: "private",
      members: ["João Silva", "Maria Santos", "Pedro Costa"],
      messages: [
        {
          id: 1,
          sender: "Pedro Costa",
          content: "Pessoal, preciso de ajuda com a configuração do banco de dados.",
          timestamp: "2024-01-25 10:30",
          type: "text",
        },
      ],
    },
  ]